import re

d = {
    "Activision": "ATVIlogo small.png",
    "Treyarch": "3arclogo small.png",
    "Infinity Ward": "Infinity Wardlogo small.png",
    "Sledgehammer Games": "Sledgehammer Gameslogo small.png",
    "Xbox": "Xboxlogo small.png",
    "PlayStation": "pslogo small.png",
    "PlayStation Arena": "ps Arenalogo small.png",
    "Call of Duty Championship 2013": "Champs2013logo small.png",
    "Call of Duty Championship 2014": "Champs2014logo small.png",
    "Call of Duty Championship 2015": "Champs2014logo small.png",
    "2016 Call of Duty World League Championship": "Champs2016logo small.png",
    "2017 Call of Duty World League Championship": "Champs2017logo small.png",
    "2018 Call of Duty World League Championship": "Champs2018logo small.png",
    "Call of Duty World League Championship 2019": "Champs2019logo small.png",
    "Call of Duty XP 2011": "XPlogo small.png",
    "Major League Gaming": "MLGlogo small.png",
    "Call of Duty World League Challenger Division": "CWLCDlogo small.png",
    "CWL Japan": "COD JPlogo small.png",
    "CWL Japan Finals": "CWL Japan Finallogo small.png",
    "2016 Call of Duty World League": "CWL2016logo small.png",
    "2017 Call of Duty World League": "CWL2017logo small.png",
    "2018 Call of Duty World League": "CWL2018logo small.png",
    "2019 Call of Duty World League": "CWL2018logo small.png",
    "Call of Duty League 2020": "CDL2020logo small.png",
    "Call of Duty Challengers": "CDClogo small.png",
    "Call of Duty League City Circuit": "CDLCClogo small.png",
    "New York Subliners": "NYlogo small.png",
    "AGN Events": "AGN Eventslogo small.png",
    "AM2Pro": "A2Plogo small.png",
    "Anicend": "Anicendlogo small.png",
    "ArenaOn": "ArenaOnlogo small.png",
    "ArenaOn": "ArenaOn PLlogo small.png",
    "ArenaOn": "ArenaOn Série Alogo small.png",
    "ArenaOn": "ArenaOn Série Blogo small.png",
    "Australian Cyber League": "ACLlogo small.png",
    "Axis eSports": "Axis eSportslogo small.png",
    "Battle of Amsterdam": "BoAlogo small.png",
    "Blackout After Dark": "BlackoutAfterDarklogo small.png",
    "Brazil Game Show": "Brazil Game Showlogo small.png",
    "BoomTV": "BoomTVlogo small.png",
    "Brazilian Series of Gamers": "BSOGlogo small.png",
    "Campeonato Sul-Americano 2019": "Campeonato Sul-Americano 2019logo small.png",
    "Cdiscount": "Cdislogo small.png",
    "Checkmate Gaming": "Checkmate Gaminglogo small.png",
    "Checkmate Gaming": "Checkmate Gaming SGLlogo small.png",
    "CLT Esports": "CLT Esportslogo small.png",
    "Crown": "Crownlogo small.png",
    "CyberGamer": "CGlogo small.png",
    "CyberGamer": "CGPLlogo small.png",
    "COD JP": "COD JPlogo small.png",
    "CPC": "2019 CPClogo small.png",
    "Connect To Play": "CTPlogo small.png",
    "Divince Events": "Divincelogo small.png",
    "Doesplay": "Doesplaylogo small.png",
    "Dexerto": "Dexerto.png",
    "Doritos": "Doritoslogo small.png",
    "DreamHack": "DHlogo small.png",
    "eBash": "eBashlogo small.png",
    "EGLX": "EGLXlogo small.png",
    "ELEAGUE": "ELEAGUElogo small.png",
    "eParadise": "eParadiselogo small.png",
    "ESL": "ESLlogo small.png",
    "Esports Arena": "ESAlogo small.png",
    "eSports Guatemala": "EGlogo small.png",
    "Esports Universe": "ESPUlogo small.png",
    "ESPU ACL": "ESPU ACLlogo small.png",
    "Esports Wolrd Convention": "ESWClogo small.png",
    "ETG": "ETGlogo small.png",
    "European Esports Event": "EEE.png",
    "European Esports Gaming": "EEGlogo small.png",
    "European Gaming League": "EGLlogo small.png",
    "European Gaming Organisation": "EGOlogo small.png",
    "Esports Open Tours": "ETOlogo small.png",
    "Febrage": "Febragelogo small.png",
    "Furious Challenge": "Furious Challengelogo small.png",
    "French Cup Organization": "SFCOlogo small.png",
    "Gamergy": "Gamergylogo small.png",
    "Gamers Assembly": "GAlogo small.png",
    "GameBattles": "GBlogo small.png",
    "MLG GameBattles": "MLG GBlogo small.png",
    "GAME eSports": "GAMElogo small.png",
    "GameStop": "GameStoplogo small.png",
    "Gamepolis": "Gamepolislogo small.png",
    "Gameturnier": "Gameturnierlogo small.png",
    "Gargula Gaming": "Gargulalogo small.png",
    "Gfinity": "Gfinitylogo small.png",
    "GGOLT": "GGOLTlogo small.png",
    "Helix eSports": "Helixlogo small.png",
    "Hitch": "Hitchlogo small.png",
    "Insomnia": "Insomnialogo small.png",
    "Ishoni Esports": "Ishonilogo small.png",
    "Isurus Gaming Series": "IGSlogo small.png",
    "KFC Gaming": "KFC_Gaminglogo small.png",
    "King of the Couch": "KOTClogo small.png",
    "KontrolFreek Showdown": "KontrolFreek Showdownlogo small.png",
    "Latam Pro League": "LatamProLeaguelogo small.png",
    "Liga de Videojuegos Profesional": "LVPlogo small.png",
    "Machinima": "Machinimalogo small.png",
    "Madrid Gaming Experience": "MGElogo small.png",
    "Major Mexican League": "MMLlogo small.png",
    "MYCG Esports": "MYCGlogo small.png",
    "MES Events": "MESlogo small.png",
    "Mettlestate Pro Series": "MPSlogo small.png",
    "Midwest Arena Esports": "MAElogo small.png",
    "Modern Warfare Streamer Invitational 2019": "Modern Warfare Streamer Invitational 2019logo small.png",
    "Ministry of Game": "MoGlogo small.png",
    "National Gaming Events": "NGElogo small.png",
    "National Gaming League": "NGL_small.png",
    "National Gaming League": "NGL_Masters_Division_small.png",
    "Owayo": "Owayologo small.png",
    "PlayStation World War II": "PSWW2logo small.png",
    "PvP Live": "PvP Livelogo small.png",
    "Red Bull AdrenaLAN": "Red Bull AdrenaLANlogo small.png",
    "Red Bull Strijders-Rivals": "RedBull Strijders-Rivalslogo small.png",
    "Reflex GT": "RGTlogo small.png",
    "Scuf Gaming": "Scuflogo small.png",
    "SoCal eSports": "SoCal eSportslogo small.png",
    "SocialNAT": "SocialNATlogo small.png",
    "SkyLAN": "SkyLANlogo small.png",
    "Team Beyond": "Team Beyondlogo small.png",
    "Team Liquid": "Liquidlogo small.png",
    "TexasCOD": "TexasCODlogo small.png",
    "Temporada de Juegos": "Temporada De Juegoslogo small.png",
    "The Main Event": "TheMainEventlogo small.png",
    "TorontoXP": "TXPlogo small.png",
    "Totinos Invitational": "TIlogo small.png",
    "Twitch": "Twitchlogo small.png",
    "UGC": "UGClogo small.png",
    "UMG": "UMGlogo.png",
    "VAL": "VALlogo small.png",
    "VS Gaming": "VS Gaminglogo small.png",
    "WhatYouPlay": "WYPSClogo small.png",
    "World Gaming": "World Gaminglogo small.png",
    "WSOE": "WSOElogo small.png",
    "XGames": "XGameslogo small.png",
    "XP Esports Queensland": "XP Esports Queenslandlogo small.png",
    "Players Portal": "Free_Agentlogo_std.png",
}

with open('league sprite data.txt', encoding="utf-8") as f:
    lines = f.readlines()

lookup = {}

for line in lines:
    logo = re.search(r'"(.+?)"', line)[1]
    pos = re.search(r'pos = ([0-9]*)', line)[1]
    lookup[logo] = pos

t = []

for league in d.keys():
    file = d[league].replace('.png', '')
    pos = lookup[file]
    t.append('\t\t["{}"] = {{ pos = {}, section = 1 }},'.format(league, pos))

with open('league sprite data new.txt', 'w', encoding='-utf8') as f:
    f.write('\n'.join(t))
